# -*- coding: utf-8 -*-
"""Copy of Intro_to_Python_II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K2FUTlvUqanS1Nu2-gzuwQSpwoRPzezN

# **Lab 2 - Introduction to Python programming II**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab2"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="Cole"

last_name="Russon"

# Enter your Math 215 section number in between the quotation marks. 

section_number="001"  

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="crusson"

"""**Problem 1**"""

first_elem=1   # Replace the value of 0 with the number described in Problem 1.

"""**Problem 2**"""

def sum_list(L):
  # Put your code here. 
  sum=0
  for i in range(len(L)):
    sum=sum+L[i]
  return sum # Put your return value here.

"""**Problem 3**"""

def list_relu(L):
  new_list=L.copy()  # Remember to create a copy of your list.  After this lab you'll need to remember to do it on your own.
  # Put your code here. 
  for i in range(len(new_list)):
    if (new_list[i]<0):
      new_list[i]=0
  return new_list # Put your return value here.

"""**Problem 4**"""

import numpy as np  # Importing NumPy

my_var=((np.exp(5))-(np.log(np.sqrt(5))))/(np.exp(np.cos(3))) # Replace the value of 0 with the required value from Problem 4.

"""**Problem 5**"""

my_vect_var=np.array([(83/24),(17/8),(-35/12),(17/8),(83/24)])  # Replace the value of 0 with the required value from Problem 5.

"""**Problem 6**"""

def first_rpt(M):
  new_matrix=M.copy()  # Remember to create a copy of your matrix.  After this lab you'll need to remember to do it on your own.
  # Put your code here. 
  for i in range(len(M)):
    new_matrix[i,:]=new_matrix[0,:]
  return new_matrix # Put your return value here.

"""**Problem 7**"""

def matrix_sum(M):
  # Put your code here. 
  num_rows=len(M)
  num_col=len(M[0,:])
  sum=0
  for i in range(num_rows):
    for j in range(num_col):
      sum=M[i,j]+sum
  return sum # Put your return value here.

"""**Problem 8**"""

long_list=[0.5**i for i in range(1,101)]   # Replace the value of 0 with the required list from Problem 8.

"""**Problem 9**"""

very_long_list=[j**i for i in range(1,100) for j in range(1,4)]   # Replace the value of 0 with the required list from Problem 9.

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.
"""